apiVersion: apps/v1
kind: Deployment
metadata:

  name: myresumeapp
  labels: 
    app: myresumeapp

spec:
  replicas: 1
  selector:
    matchLabels:

      app: myresumeapp
  template:
    metadata:
      labels:
        app: myresumeapp
    spec:
      containers:
      - name: myresumeapp
        image: {{ .Values.appimage}}:{{ .Values.apptag}}
        ports:
        - name: myresumeapp-port

          containerPort: 8080
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup myresumedb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup myresumecache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']

