AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation to create an S3 Bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-first-bucket
      AccessControl: Private

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3Bucket
